
project_id = "ed2c44ac-e4ef-4d99-bf09-af672cd97196"

[functions.send-birthday-reminders]
verify_jwt = false

[functions.send-catchup-reminders]
verify_jwt = false

[functions.send-nudge]
verify_jwt = false

[functions.send-date-ideas]
verify_jwt = false

[functions.cron-job-diagnostics]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = false
