
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xzpnizupsygzilcibstc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6cG5penVwc3lnemlsY2lic3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMzU2NzIsImV4cCI6MjA2NTYxMTY3Mn0.v0B5K7t0e4w58REnQLqjM3mEpRBm6BcboCabileNWYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
